texts = [
    "ARNet is a powerful language model.",
    "This is an example of a longer sentence that demonstrates the capability of handling variable-length inputs.",
    "Another example here with different length.",
    "ARNet is designed for language modeling tasks and can process sentences of varying lengths.",
    "Let's see how it performs on this challenging task with longer sequences and more complex structures.",
    "The model should be able to handle these inputs without any issues now.",
     "ARNet is a powerful language model.",
    "This is an example of a longer sentence that demonstrates the capability of handling variable-length inputs.",
    "Another example here with different length.",
    "ARNet is designed for language modeling tasks and can process sentences of varying lengths.",
    "Let's see how it performs on this challenging task with longer sequences and more complex structures.",
    "The model should be able to handle these inputs without any issues now.",
     "ARNet is a powerful language model.",
    "This is an example of a longer sentence that demonstrates the capability of handling variable-length inputs.",
    "Another example here with different length.",
    "ARNet is designed for language modeling tasks and can process sentences of varying lengths.",
    "Let's see how it performs on this challenging task with longer sequences and more complex structures.",
    "The model should be able to handle these inputs without any issues now.",
     "ARNet is a powerful language model.",
    "This is an example of a longer sentence that demonstrates the capability of handling variable-length inputs.",
    "Another example here with different length.",
    "ARNet is designed for language modeling tasks and can process sentences of varying lengths.",
    "Let's see how it performs on this challenging task with longer sequences and more complex structures.",
    "The model should be able to handle these inputs without any issues now.",
     "ARNet is a powerful language model.",
    "This is an example of a longer sentence that demonstrates the capability of handling variable-length inputs.",
    "Another example here with different length.",
    "ARNet is designed for language modeling tasks and can process sentences of varying lengths.",
    "Let's see how it performs on this challenging task with longer sequences and more complex structures.",
    "The model should be able to handle these inputs without any issues now.",
     "ARNet is a powerful language model.",


    # Add more texts here...
]